### ISSUE TITLE
Cloudformation script fails when the user's Boomi password contains certain characters

### ISSUE THREAD

**Issue by davehalladay** [aws-quickstart/quickstart-boomi-molecule#12]
I was having trouble getting this cloudformation script to run successfully, it would fail on creation of MoleculeNode1. After some troubleshooting, I found out that in the 010_install_atom command, the bash command to run the molecule_install.sh script was failing because my Boomi password contained the character ")". I was able to get the script to run by changing my Boomi password to only contain underscore special characters. I would recommend flagging that as a potential issue for new users or if that command can be modified to handle those characters in the password that would save someone else a headache!

**Comment by cdelcastillo** [comment]
I actually am running into the same issue where the Cloudformation deployment is failing at 010_install_atom.  I can't see any errors that should be causing this.
I updated my password just in case, but still same error.  I am seeing following in the logs:

```
[ERROR] com.install4j.runtime.beans.actions.misc.AddVmOptionsAction [ID 16058]: launcher file null does not exist.
        Execute action not successful after 0 ms
[INFO] com.install4j.runtime.beans.actions.desktop.CreateProgramGroupAction [ID 7]: Execute action
       Property linkDirectory: /usr/local/bin
       Property programGroupName: 
       Property allUsers: true
       Property unixSymlinks: true
       Property categories: Application
       Property programGroupEntryConfigs: [ProgramGroupFileConfig{target=doc/Forums.url, arguments='', runAsAdministrator=false}, ProgramGroupFileConfig{target=doc/Help.url, arguments='', runAsAdministrator=false}, ProgramGroupFileConfig{target=doc/Home.url, arguments='', runAsAdministrator=false}]
       Property uninstallerMenuName: Molecule Uninstaller
       Property addDefaultLauncherLinks: true
       Property addUninstaller: true
       Property failForSymlinksNotCreated: false
       Property unixMenuEntries: true
       Property rollbackSupported: true
       Execute action successful after 1 ms
[INFO] com.install4j.runtime.beans.actions.desktop.RegisterAddRemoveAction [ID 8]: Execute action
       Property iconSource: Installer icon
       Property itemName: Boomi AtomSphere - awstest01
       Property icon: null
       Property persistentProperties: {}
       Property rollbackSupported: true
       Execute action successful after 1 ms
[INFO] com.boomi.install.MoleculeIdAction [ID 94]: Execute action
       Property message: Retrieving Container ID
       Property rollbackSupported: true
[ERROR] com.boomi.install.MoleculeIdAction [ID 94]: Execute action not successful after 59 ms
[INFO] com.boomi.install.MoleculeIdAction [ID 94]: Rollback action
       Rollback action finished
```

**Comment by cdelcastillo** [comment]
I ran into the same error, mine, however, was due to the fact that we exceeded the number of molecules we could stand up.
Is there a way to capture these errors and put them in the log file?  We worked on this for a bit, before we decided to halt the rollback and try to run the steps in 010_install_atom manually.  That is when we were able to see the actual error.
