### ISSUE TITLE
Default temporary DIR is set to /mnt and ec2-user can not use it

### ISSUE THREAD

**Issue by Nicolas-Duriez** [aws-quickstart/quickstart-boomi-molecule#13]
When launching a job on the Boomi console, it appears the quickstart has set /mnt/ for the default temporary directory:

1. It blocks any job, as the ec2-user with which boomi is started does not have write permissions in this folder
2. it may not be totally efficient as it uses a shared EFS filesystem although boomi does not need to share this content between nodes.

Suggested solution:

1. Change the default temporary directory to /tmp/boomi/
2. Create this directory in the quickstart and ensure ec2-user can write into it

**Comment by alomakin** [comment]
Current issue, with missed permissions to local temp directory for ec2-user lays in this line: https://github.com/aws-quickstart/quickstart-boomi-molecule/blob/0d20d2e858fe9cf9927b24306959e6f425479b0a/templates/boomi-molecule.template.yaml#L393
Looks like a misprint as the same directory specified twice. As a quick fix, second directory should be `${MoleculeLocalTemp}`
