### ISSUE TITLE
While setting this up on AWS "MoleculeStack" is getting failed.

### ISSUE THREAD

**Issue by login21** [aws-quickstart/quickstart-boomi-molecule#16]
I am trying to setup boomi molecule cluster on AWS and following the steps precisely but after launching my cloud formation stack every step is successful but but my "MoleculeStack" is always failing with error 

Embedded stack arn:aws:cloudformation:us-east-2:accountid:stack/boomi-test-MoleculeStack-1MFGHBRVZ3Y1/684b9550-9b34-11ea-a5cf-02jhj927fac094 was not successfully created: The following resource(s) failed to create: [MoleculeNode1, Node4WaitCondition].

Ant help will be appreciated.

**Comment by andrew-glenn** [comment]
Usually that means there’s an issue with your Boomi account. Either a username/password issue or you’re running up against your Enterprise licenses (1 per cluster is necessary).

The other known issue is a dash in the Molecule cluster name. There’s a nuance that’s not accounted for (we discovered last week) - please leverage underscores instead.

We are iterating on the next version of this right now and these lessons learned will be reflected in better error handling (etc).

In the interim, happy to help navigate these lessons learned. :)

**Comment by login21** [comment]
Thank you for the information Andrew. Yes It was issue with my account. It worked after fixing my account now. Thank You.
