### ISSUE TITLE
Application Load Balancer support?

### ISSUE THREAD

**Issue by JanneEN** [aws-quickstart/quickstart-boomi-molecule#3]
Why does the Quick Start Template use the old Classic Load Balancer instead of the current Application Load Balancer? Does Boomi Atom use some features that require the Classic Load Balancer? AWS recommends use of ALB over ELB in most normal web use cases. Also, ALB offers many more features.

Are there plans to introduce the ALB to the template in the future?

**Comment by andrew-glenn** [comment]
@JanneEN 

ALB Support was something that we originally looked at. ELB Classic was included (for now) during the development process as a result of several milestone decisions.

However, we're re-evaluating ALB support and I anticipate that we'll migrate over soon.

**Comment by cdelcastillo** [comment]
Are there known issues with using alb?

**Comment by andrew-glenn** [comment]
No known issues. However, we’re happy to iterate fast if you run across any.

**Comment by andrew-glenn** [comment]
ALB is now present; closing.
