### ISSUE TITLE
Error when starting up MoleculeNode1

### ISSUE THREAD

**Issue by cellsignal-m** [aws-quickstart/quickstart-boomi-molecule#48]
Am getting the following error:
Received FAILURE signal with UniqueId i-xxxxxxxxx
After CREATE_IN_PROGRESS for MoleculeNode1 using the latest quickstart.

**Comment by cellsignal-m** [comment]
Found this in the logs:
`[   68.675127] cloud-init[12193]: --------------------------------
[   68.685327] cloud-init[12193]: [INFO] Dependencies Met!
[   68.693147] cloud-init[12193]: [INFO] Start OS Updates
[   69.047035] cloud-init[12193]: Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
[   69.057516] cloud-init[12193]: You need to be root to perform this command.
[   69.072542] cloud-init[12193]: [INFO] Finished OS Updates
[   69.080019] cloud-init[12193]: [INSTALL aws-cfn-bootstrap tools]
[   69.080887] cloud-init[12193]: cp: cannot create regular file ‘/etc/profile.d/opt-aws.sh’: Permission denied
[   69.081672] cloud-init[12193]: ln: failed to create symbolic link ‘/usr/bin/cfn-elect-cmd-leader’: Permission denied
[   69.081838] cloud-init[12193]: ln: failed to create symbolic link ‘/usr/bin/cfn-get-metadata’: Permission denied
[   69.081980] cloud-init[12193]: ln: failed to create symbolic link ‘/usr/bin/cfn-hup’: Permission denied
[   69.082099] cloud-init[12193]: ln: failed to create symbolic link ‘/usr/bin/cfn-init’: Permission denied
[   69.082271] cloud-init[12193]: ln: failed to create symbolic link ‘/usr/bin/cfn-send-cmd-event’: Permission denied
[   69.082392] cloud-init[12193]: ln: failed to create symbolic link ‘/usr/bin/cfn-send-cmd-result’: Permission denied
[   69.082508] cloud-init[12193]: ln: failed to create symbolic link ‘/usr/bin/cfn-signal’: Permission denied
[   69.434098] cloud-init[12193]: Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
[   69.443427] cloud-init[12193]: You need to be root to perform this command.`
Not sure if this is related.

**Comment by cellsignal-m** [comment]
Also this:
`[  OK  ] Started Dynamically Generate Message Of The Day.
[  145.769011] cloud-init[12193]: Traceback (most recent call last):
[  145.769308] cloud-init[12193]: File "/usr/lib64/python2.7/logging/__init__.py", line 891, in emit
[  145.771432] cloud-init[12193]: stream.write(fs % msg.encode("UTF-8"))
[  145.772540] cloud-init[12193]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 50: ordinal not in range(128)
[  145.772722] cloud-init[12193]: Logged from file util.py, line 502
[  145.952731] cloud-init[12193]: Traceback (most recent call last):
[  145.953721] cloud-init[12193]: File "/usr/lib64/python2.7/logging/__init__.py", line 891, in emit
[  145.953877] cloud-init[12193]: stream.write(fs % msg.encode("UTF-8"))
[  145.954018] cloud-init[12193]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)
[  145.954170] cloud-init[12193]: Logged from file util.py, line 502
[  145.964100] cloud-init[12193]: Error occurred during build: Command 011_install_atom failed`

**Comment by C2BB** [comment]
Running into exactly the same issue, did you ever resolve?

**Comment by davmayd** [comment]
Can you please see https://github.com/aws-quickstart/quickstart-boomi-molecule/pull/50 and try again?

**Comment by andrew-glenn** [comment]
Closing as #50 is believed to resolve this. Please reopen if you find otherwise.
