### ISSUE TITLE
Lambda logs Boomi password in plaintext

### ISSUE THREAD

**Issue by JanneEN** [aws-quickstart/quickstart-boomi-molecule#5]
The Lambda function that is part of the CloudFormation template logs the Boomi admin password given as a template parameter in plaintext in CloudWatch logs. It is included in the Received event: message as json dump. 

The password should be obfuscated or not logged at all.

**Comment by andrew-glenn** [comment]
@JanneEN 
I just pushed a commit to address this. This issue will auto-resolve after our CI pipeline promotes the change to the master branch.
