### ISSUE TITLE
Guide on how to set-up default DNS / SSL configurations.

### ISSUE THREAD

**Issue by kckarana** [aws-quickstart/quickstart-boomi-molecule#8]
Reading on the quick start guide I noticed that the DNS/SSL configuration section is a bit unclear on which default domain we could use for the required parameters. Is there a chance that you could give some more information on this?

**Comment by andrew-glenn** [comment]
@kckarana  - Sure. 

The intention there is to mandate the use of an SSL Certificate. If you have an ACM SSL that you wish to use, then you can supply its ARN in the SSLCertificateId parameter.

On the other hand, if you don't have a pre-existing SSL, you would supply a FQDN, and the Route53 Hosted Zone ID for that FQDN. The templates are designed to provision and validate the SSL for you, in this scenario. The R53 Zone ID is needed as part of the validation process.

Hope that helps!

**Comment by everyonce** [comment]
It also appears that you're only wanting the input guid from the ARN, not a full ARN - might be helpful to be clear about that on the parameter descriptions.

**Comment by everyonce** [comment]
> It also appears that you're only wanting the input guid from the ARN, not a full ARN - might be helpful to be clear about that on the parameter descriptions.

this seems to be corrected, or something i did made it work now.  Also would be good to note that the certificate ARN needs to be for a cert with a single name, not a wildcard.

**Comment by kckarana** [comment]
Hi guys,

I was trying to figure out a way to give a self-signed SSL certificate. Unfortunately importing it into AWS ACM didn't solve my problem and I was getting error while running the template.

I then thought of IAM. I imported the certificate in there and everything worked!
